// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV9zI-cYdabexEjsMbbepwG-OUT4lho8U',
    appId: '1:435201146577:web:e4d53bc56c6dcdedbd0ff0',
    messagingSenderId: '435201146577',
    projectId: 'luround-japhet',
    authDomain: 'luround-japhet.firebaseapp.com',
    storageBucket: 'luround-japhet.appspot.com',
    measurementId: 'G-FJMZENNT1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUrHViZVSbJ7p8jN53iIiJ8mDnlO5H1Q',
    appId: '1:435201146577:android:8589139bbe3af271bd0ff0',
    messagingSenderId: '435201146577',
    projectId: 'luround-japhet',
    storageBucket: 'luround-japhet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2pMlwZ-VzRA5cMXhUxzSoxqG71pYU6A',
    appId: '1:435201146577:ios:a1fcbd9ae9343cdebd0ff0',
    messagingSenderId: '435201146577',
    projectId: 'luround-japhet',
    storageBucket: 'luround-japhet.appspot.com',
    iosBundleId: 'com.example.luround',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj2pMlwZ-VzRA5cMXhUxzSoxqG71pYU6A',
    appId: '1:435201146577:ios:1d3cdd5ebc3ffb5dbd0ff0',
    messagingSenderId: '435201146577',
    projectId: 'luround-japhet',
    storageBucket: 'luround-japhet.appspot.com',
    iosBundleId: 'com.example.luround.RunnerTests',
  );
}
