// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKe2z58TPfrMHHPgdeopFQC2JUQQ3TkSw',
    appId: '1:747612609885:web:4cece214e490ad7b2f1cb4',
    messagingSenderId: '747612609885',
    projectId: 'luround-fb183',
    authDomain: 'luround-fb183.firebaseapp.com',
    storageBucket: 'luround-fb183.appspot.com',
    measurementId: 'G-JS7WZHL20R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_8_92ufVyq_BFTlT3iWzyLF61_7R8ks',
    appId: '1:747612609885:android:d718c60c3739a31c2f1cb4',
    messagingSenderId: '747612609885',
    projectId: 'luround-fb183',
    storageBucket: 'luround-fb183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExb1GAVglDoAlXZS2O1lmdGTLO5vUDYo',
    appId: '1:747612609885:ios:8192771122695f7d2f1cb4',
    messagingSenderId: '747612609885',
    projectId: 'luround-fb183',
    storageBucket: 'luround-fb183.appspot.com',
    iosBundleId: 'com.example.luround',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExb1GAVglDoAlXZS2O1lmdGTLO5vUDYo',
    appId: '1:747612609885:ios:04b062e53c6cefd52f1cb4',
    messagingSenderId: '747612609885',
    projectId: 'luround-fb183',
    storageBucket: 'luround-fb183.appspot.com',
    iosBundleId: 'com.example.luround.RunnerTests',
  );
}
